### ISSUE TITLE
Renaming package name

### ISSUE THREAD

**Issue by lepture** [matthiask/django-authlib#2]
Hi, I found your package django-authlib has a conflict with https://github.com/lepture/authlib

Your package is registered as `django-authlib` (I do want this package name too) on PyPI, but the module name is authlib, which has conflict with my package. Would you consider rename it to `django_authlib`?

BTW, consider using [authlib](https://github.com/lepture/authlib) to power your library, it has a simple built-in Django support: https://docs.authlib.org/en/latest/client/frameworks.html#module-authlib.django.client

**Comment by matthiask** [comment]
Hi,

- It's not clear to me why I would use your authlib instead of https://github.com/requests/requests-oauthlib the OAuth client? Also, django-authlib is used in commercial projects as well, and AGPL is out of the question for those. I release almost everything as open source anyway, but haven't used GPL-type licenses for probably more than 10 years now.
- It's true that the project cannot be installed alongside your authlib into the same virtualenv. However, I don't see how this is a problem since I can't envision a scenario where someone would want to use both authlib and django-authlib in the same project
- "I want this too" is not a good enough reason for giving up the package name on PyPI. It is an actively maintained library of authentication utilities for Django, therefore django-authlib. Since your library supports more frameworks, not only Django, let me suggest you use python-authlib (similar to django-social-auth which was renamed to python-social-auth later -- https://github.com/python-social-auth) or even your current plain authlib package name, nothing wrong with that. Of course things would possibly be different if maintenance stopped or something.

Thanks.

**Comment by matthiask** [comment]
I'm revisiting this, because your package seems to be maintained much more actively; I'll probably rename the Python module to `django_authlib` as suggested. I don't like the `django_` prefix too much but it's a minor concern, really.
